# AUTOGENERATED! DO NOT EDIT! File to edit: gradiotest.ipynb.

# %% auto 0
__all__ = ['is_cat', 'learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% gradiotest.ipynb 4
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% gradiotest.ipynb 8
learn = load_learner('model.pkl')

# %% gradiotest.ipynb 10
categories = ("Dog", "Cat")

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% gradiotest.ipynb 12
image = gr.inputs.Image(shape=(192, 192))
label = gr.outputs.Label()
examples = ['dog.jpeg', 'cat.jpeg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
